# Generated by Django 5.2.5 on 2025-11-11 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nomeCategoria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='TipoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('ECONOMIA', 'Economia')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPercentual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('NECESSIDADES', 'Necessidades'), ('DESEJOS', 'Desejos'), ('POUPANCA', 'Poupança')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id_movimentacao', models.AutoField(primary_key=True, serialize=False)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipoMovimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.tipomovimentacao')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipoMovimentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.tipomovimentacao'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipoPercentual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.tipopercentual'),
        ),
    ]
