# Generated by Django 5.2.5 on 2025-11-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_categoria_tipomovimentacao_tipopercentual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='tipoPercentual',
        ),
    ]
