# Generated by Django 5.2.5 on 2025-11-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_remove_categoria_tipopercentual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='tipoMovimentacao',
        ),
    ]
