# Generated by Django 5.2.5 on 2025-11-11 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_remove_movimentacao_tipomovimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_movimentacao',
            field=models.DateTimeField(),
        ),
    ]
