# Generated by Django 5.2.5 on 2025-11-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0006_movimentacao_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='criado_em',
            field=models.DateField(auto_now_add=True),
        ),
    ]
