# Generated by Django 5.2.5 on 2025-11-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0007_alter_movimentacao_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_movimentacao',
            field=models.DateField(),
        ),
    ]
