# Generated by Django 5.2.5 on 2025-11-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0008_alter_movimentacao_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
